# Workflow checks if pip can build py_cui on windows.

name: build pkg

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
  pull_request:
    branches:
      - master
    paths:
      - '**.py'

jobs:
  windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Build package
      run: |
        pip install .